In [1]:
import pandas as pd
from sklearn import model_selection
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
#from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
dataset=pd.read_csv('Iris.csv')
array = dataset.values
X = array[:,1:5]
Y = array[:, 5]
test_train_split_size = 0.20
seed =10
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=seed)
#dt = DecisionTreeClassifier(max_depth=6, random_state=seed)
dt = SVC()
      # Performing training
dt.fit(X_train, Y_train)
predictions = dt.predict(X_test)
Accuracy = accuracy_score(Y_test, predictions)
print("\nAcuuracy\n", Accuracy)
Classification_Report = classification_report(Y_test, predictions)
Confusion_Matrix = confusion_matrix(Y_test, predictions)
print("\nConfusion Matrix\n", Confusion_Matrix)
print("\nClassification Report\n", Classification_Report)
#Save the model as Pickle
import pickle
with open(r'rf1.pkl','wb') as model_pkl:
    pickle.dump(dt, model_pkl, protocol=2)



Acuuracy
 0.9666666666666667

Confusion Matrix
 [[10  0  0]
 [ 0 12  1]
 [ 0  0  7]]

Classification Report
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      0.92      0.96        13
 Iris-virginica       0.88      1.00      0.93         7

       accuracy                           0.97        30
      macro avg       0.96      0.97      0.96        30
   weighted avg       0.97      0.97      0.97        30



In [2]:
pd. __version__

'1.3.4'

In [ ]:
sklearn.__version__

NameError: name 'sklearn' is not defined

In [ ]:
import sklearn
sklearn.__version__

'0.24.2'

In [ ]:
time.__version__

AttributeError: module 'time' has no attribute '__version__'

In [ ]:
import pickle
pickle.format_version

'4.0'

In [ ]:
import flask
flask.__version__

'1.1.2'

In [ ]:
import numpy
numpy. __version__

'1.20.3'

In [ ]:
import python
print(python_version())

ModuleNotFoundError: No module named 'python_version'

In [ ]:
from platform import python_version 
print(python_version())

3.9.7


In [ ]:
pip install sklearn==1.1


Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement sklearn==1.1 (from versions: 0.0)
ERROR: No matching distribution found for sklearn==1.1
